jobs:
- job: Windows
  pool:
    vmImage: vs2017-win2016
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.5'

  - script: gem install bundler
  - script: bundle install --retry=3 --jobs=4

  - script: |
      SET FASTLANE_ITUNES_TRANSPORTER_PATH="C:/tmp"
      SET FASTLANE_ITUNES_TRANSPORTER_PATH
    displayName: 'set ENV variables'

  - script: bundle exec fastlane execute_tests
    displayName: 'bundle exec fastlane execute_tests'

- job: macOS
  pool:
    vmImage: xcode9-macos10.13
  steps:
  - script: |
      gem install bundler
      bundle install --retry=3 --jobs=4
    displayName: 'bundle install'

  - script: |
      export FASTLANE_ITUNES_TRANSPORTER_PATH="/tmp"
      echo $FASTLANE_ITUNES_TRANSPORTER_PATH
    displayName: 'set ENV variables'

  - script: bundle exec fastlane execute_tests
    displayName: 'bundle exec fastlane execute_tests'
  
- job: Linux
  pool:
    vmImage: ubuntu-16.04
  steps:
  - task: UseRubyVersion@0
    inputs:
      versionSpec: '>= 2.5'

  - script: |
      gem install bundler
      bundle install --retry=3 --jobs=4
    displayName: 'bundle install'

  - script: |
      export FASTLANE_ITUNES_TRANSPORTER_PATH="~"
      echo $FASTLANE_ITUNES_TRANSPORTER_PATH
    displayName: 'set ENV variables'
    
  - script: |
      sudo apt-get install libssl-dev
      wget https://github.com/downloads/mackyle/xar/xar-1.6.1.tar.gz
      tar -xzf xar-1.6.1.tar.gz \
        && mv xar-1.6.1 xar \
        && cd xar \
        && ./autogen.sh --noconfigure \
        && ./configure \
        && make 
    displayName: 'install xar' 

  - script: bundle exec fastlane execute_tests
    displayName: 'bundle exec fastlane execute_tests'

